name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: [ubuntu-latest, macos, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: install cxxtest
      run: sudo apt install -y cxxtest
    - name: build library
      run: make library
    - name: make thrain
      run: make
    - name: make tests
      run: make tests
    - name: run tests
      run: ./tests/tests.out
